sudo: required
notifications:
  email: false
services:
- docker
language: python
python:
- 3.6
git:
  depth: false
script:
- make build
- make push
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis-deploy.sh
  on:
    branch: master
env:
  global:
  - secure: k56SmGXxs9eWY//h8lbCoHAYKWiCuM7oAR0V7M0VZ/y8PsYf8quV1K7kgEvO/92+0U69CNfvUQb2PJNuXQVfOYRX/e3jrpZBpMSLunK/QThVdHI6jkWVWjnPPon/uPKlWkHhXP+dOmeHrZ0s4jAauvwHCLG2SLKHMXlFWideG/ge2ah6Q0MvxefhrAQOsf1h6ITgLj0qZXWjne0OZynB697xKKfGXFVsgYWX7WDkIS3doOzy/AFXC3LSk/dY+Si9dtpbRZEeuZOJ3v/JfjCY6Pj6SP8okt7tJEMSbpYiA2kYHjFfiZxRTybDMy3dNmI6Zlnv9Q0ZTMQvENB34ptOIbOkds3vr6LXxDtJqQjZY5QbxzgsZJyYby0lNlejMbpkseIH5dtduL+qIj7lsEilkZMJVUPzQWPly5YETm/sua8mggJCSfzxxhDOP1igpfeDkynrPWn9PVJtTtdkF7/NmLPUxPi+nXH7EgrR61Tlfz7qvV9h5Qwnub+D1jR5ekMkkh7OiK06RiesfATqKZlKTM3xvjnWPF7uh5lE60Zat6fhg0cYP3osxpQMjRD40JB0neRL2E6I7M0Rj7LMSTymCiltkGHOJ39081HMG5i6TnnvczGdeDvQUDAD/DX1MdPQzsR5OUgkQiOCD7XUNFHyt/UlowvAUnm4oRUp6tOQiio=
  - secure: CeL3gzlEs26cQyoqKwisN9YLbDW+/4Vuct4yKcvUV2YChAUicEYI3hQhPDh423BD5uQI+8h0IlwZUrY9AM3uW6J9uTud+Jp0Kg2Cg0NlR7IgQQu7kPlkSNGQr9umKqsnAZ9z5R3fBXT+BzEpQOmv39DoWSrz1ndrN/MAwtKgnTEUQ6apVd4eyIfY3Jo/OcqyDau8s3PvTehU9C/uWnapfKTArjygNHO27bxe5BioxKFR1z5WcIVzl4L5k97KxjM2+ujGUh5w8031Xbv/+vZsoUf2ELLkddr4j+Sq9h5TDfsEyvmClCYs9ITf+fQMgl0l1+2VD1FO3G1tSgrOZsmiDQ7rv3MMZzbee2l9KpLYl5Savc9vG7o3GAYP7ngY1OJRnN0XrlTpbToLKvqlDWDKmB0YUSHLVxmGA6sfxSqLB1dJzZvWi+Yb23LWCMPUG5Nbp7Nv+FbYdc3azKoA3ulY5BqRmWriDygly8nyib2hPmK5+AnEgcF3R+cPX+WIdd52pY6NTAwO/ZcQ9TIs/Qa0JsGCKAEzGrWFKSvHXSib+6N2TPevxORSwRMZk5KuLQqktOM8chxRai0wyy+dAbQ+oiPYG00bi0A5Gb3dbt3+eftaSzyj2mKxnEw3SliDS2vkBKDHa9o+vsCEHhkcCR+2He/xo4tB0bZi/vUOo1H/Pc4=
